### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thanhbao0408**
Add my name - Bao Nguyen to the list.

### CODE REVIEW

**Comment by sarthology** [comment]
Hey Avenger 😎

Tell me your Powers. 💪🏼

**Comment by thanhbao0408** [comment]
I'm a Web developer in the day, but when the night comes, I become a hungry monster who seeks for gaming-related things. 👻👻👻
I can work well with ASP .NET and Unity. I'm learning node.js and react.js as a part of my career path.

**Comment by sarthology** [comment]
Ooo, a ninja.

Which tribe you represent, JavaScript or Python ?

**Comment by thanhbao0408** [comment]
Well. I wear a mask of an ASP .NET developer and have the skills to deal with those Javascript aliens 👽

**Comment by sarthology** [comment]
Haha, nice. Let's chat at Telegram username: Sarthology

**Pull request closed without merging**
