### PR TITLE
Add name in the list

### PR DESCRIPTION
**Pull request by Stereoraj**
Looking forward to join the multiverse.

### CODE REVIEW

**Comment by sarthology** [comment]
Hey Avenger 😎

Tell me your Powers. 💪🏼

**Comment by Stereoraj** [comment]
My power/love lies in Javascript stack. I can code in React, Node. FullStack basically. Also have been lately looking into GraphQL and it looks amazing.

**Comment by sarthology** [comment]
Welcome to the team

**Comment by Stereoraj** [comment]
> Welcome to the team

Thankyou very much.

**Pull request merged**
